apiVersion: v1                    
kind: Namespace
metadata:
  name: openshift-storage                             
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: ocs-application
  namespace: openshift-storage
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - ocs-application
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: ocs
  labels:
    app: ocs-application
  name: ocs-application-subscription-0
  namespace: openshift-storage
spec:
  channel: ggithubcom-umangachapagain-applications-ns/ggithubcom-umangachapagain-applications
  placement:
    placementRef:
      kind: PlacementRule
      name: ocs-application-placement-0
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: ocs-application
  name: ocs-application-placement-0
  namespace: openshift-storage
spec:
  clusterSelector:
    matchLabels:
      'local-cluster': 'true'
