---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: umanga-busybox
  labels:
    app: umanga-busybox
  annotations:
    apps.open-cluster-management.io/github-path: busybox
    apps.open-cluster-management.io/github-branch: main
spec:
  channel: application-samples/applications
  # placement:
  #   placementRef:
  #     name: rook-application
  #     kind: PlacementRule
